### PR TITLE
(GH-189) - invalid fact correction for top scope structured fact

### LINKED ISSUE #189: Lint behaves weird when fixing a top-level structured fact reference
### What Versions are you running?

OS Version: MacOS 14.2.1 (arm64)
VSCode Version: VSCodium Version: 1.85.2
Puppet Extension Version: v1.5.1 (from the open-vsx repo)
PDK Version: 3.0.1

### What You Are Seeing?
Let's say I have the following example manifest with a (custom) top-level structured fact reference:
```puppet
$foo = $::my_structured_fact['foo']
```

When I select "Format Document" from the context menu I got this:
```puppet
$foo = $facts['my_structured_fact['foo']']
```

As you may see it's wrong syntax and it breaks the future file checks and formatting.

### What is Expected?
```puppet
$foo = $facts['my_structured_fact']['foo']
# -OR-
$foo = $facts.get('my_structured_fact.foo')
```

Though I'm not sure if it's easy to fix at all. So mostly leaving it here for your awareness.

### PR DESCRIPTION
**Pull request by jordanbreen28**
## Summary

Prior to this PR, if you had a top scope structured fact like this in your manifest `$::my_structured_fact['foo']['test']`, lint would return an invalid correction when passed the fix flag.

Now, we have altered the top_scope_facts plugin, to first check if it is a structured fact, and if one is found using regex, apply different logic to fix.

## Additional Context
Unstructured top scope fact:
```
$foo = $::my_structured_fact
```
when fixed:
```
bundle exec puppet-lint ./manifest.pp -f
FIXED: top scope fact instead of facts hash on line 1 (check: top_scope_facts)
```
```
$foo = $facts['my_structured_fact']
```

top scope structured fact (& not on allowlist):
```
$foo = $::my_structured_fact['foo']['test']
```

when fixed:
```
bundle exec puppet-lint ./manifest.pp -f
FIXED: top scope fact instead of facts hash on line 1 (check: top_scope_facts)
```
```
$foo = $facts['my_structured_fact']['foo']['test']
```
## Related Issues (if any)
Fixes #189 

## Checklist
- [x] 🟢 Spec tests.
- [x] 🟢 Acceptance tests.
- [x] Manually verified.

### CODE REVIEW

File: spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb [hunk 1]
```diff
@@ -102,6 +102,18 @@
       end
     end
 
+    context 'top scope structured fact not present on allowlist' do
+      let(:code) { "$::my_structured_fact['foo']['test']" }
```
Comment (bastelfreak) [inline spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb:106]: Will this now correct top scope variables to facts and break the code?

Comment (jordanbreen28) [reply spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb:106]: It shouldn't, the original logic for this plugin should still apply. This particular fix will only trigger if a top scope structured fact such like `$::somefact['foo']` is detected

Comment (jordanbreen28) [reply spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb:106]: does that make sense @bastelfreak? I'm happy to take on any concerns you have that this might cause further issues :)

Comment (bastelfreak) [reply spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb:106]: I think your change is fine.

But: The docs are a bit confusing:
> It assumes all top scope variables are facts. If you have top scope variables that aren't facts you should configure the [linter to ignore them](https://github.com/mmckinst/puppet-lint-top_scope_facts-check#configuring-the-check).

Okay. but why are there facts in the builtin allowlist? https://github.com/puppetlabs/puppet-lint/blob/e4863b0fda02c0bdc8f02448a41d9bc9852bb4f4/lib/puppet-lint/plugins/top_scope_facts/top_scope_facts.rb#L20

Does it allow legacy facts as topscope notation, e.g. `$::architecture`? or am I reading this wrong?

**Review by bastelfreak — APPROVED** [review]

File: spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb (hunk 1 above)
Comment (jordanbreen28) [reply spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb:106]: @bastelfreak that allowlist was implemented as part of https://github.com/puppetlabs/puppet-lint/commit/3d7e9394aa91b9d0778e66ab0e1596b946922fff which fixed a bug were legacy facts with top scope notation were getting corrected twice.
I think the idea here is the `allow` them in this plugin, so that the legacy fact plugin can correct them appropriately. :)

Comment (bastelfreak) [reply spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb:106]: Ahhhh okay. makes sense now!
